angular.module('gvmItems', [])
  .controller('GvmController', function($scope) {
    $scope.fighters = [{
          name: 'Chalstolce',
          fullname: 'Chalstolce Macabre',
          img: 'https://greyvoth.com/gvm/img/char/chalstolce_gvm_char.png',
          house: 'Dark',
          cityname: 'Ottom, Guiresphere',
          city: 'https://greyvoth.com/gvm/assets/ottom-GVM.png',
          job: 'Macabre King',
          style: 'Dark Sword Killer',
          weapon: 'God Bleeder',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/chalstolce-weapon.png',
          special: 'Dark Fury',
          personality: 'Vile',
          actionshot: 'Bleeding Cut',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '1',
          filter: 'ottom'
        },
        {
          name: 'Crin',
          fullname: 'Crin Robinson',
          img: 'https://greyvoth.com/gvm/img/char/crin_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe King',
          style: 'Light of Hope',
          weapon: 'Star Dusk',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/crin-weapon.png',
          special: 'Lit Fury',
          personality: 'Stoic',
          actionshot: 'Sword Mastery',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '2',
          filter: 'ab'
        }, {
          name: 'Lem',
          fullname: 'Lem Bevin',
          img: 'https://greyvoth.com/gvm/img/char/lem_gvm_char.png',
          house: 'Wolf',
          cityname: 'Lune, Kreis',
          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
          job: 'Wolf King',
          style: 'Hard Claws',
          weapon: 'Basilisk',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/lem-weapon.png',
          special: 'Time Stop',
          personality: 'Nervous',
          actionshot: 'Wolf Duo',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '3',
          filter: 'kreis'
        },
        {
          name: 'Yosh',
          fullname: 'Yosh Baskerville',
          img: 'https://greyvoth.com/gvm/img/char/yosh_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe Knight',
          style: 'Slicer',
          weapon: 'Rhetoric',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/yosh-weapon.png',
          special: 'The Answer',
          personality: 'Cautious',
          actionshot: 'The Robe Slayer',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Yosh-Full.png',
			bio: 'https://greyvoth.com/gvm/characters/yosh.html',
          gallery: '4',
          filter: 'ab'
        },
        {
          name: 'Samson',
          fullname: 'Samson',
          img: 'https://greyvoth.com/gvm/img/char/samson_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Boulevard Fighter',
          style: 'Dicer',
          weapon: 'Y-Calibre',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/samson-weapon.png',
          special: 'Y Knot',
          personality: 'Bold',
          actionshot: 'Y Slicer',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Samson-full.png',
			bio: 'https://greyvoth.com/gvm/characters/samson.html',
          gallery: '5',
          filter: 'u'
        },
        {
          name: 'Grandle',
          fullname: 'Grandle Robinson',
          img: 'https://greyvoth.com/gvm/img/char/grandle_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe Prince',
          style: 'Gunner',
          weapon: '9mm Handguns',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
          special: 'Robe Ammo',
          personality: 'Cocky',
          actionshot: 'Chimera Punch',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Grandle-full.png',
			bio: 'https://greyvoth.com/gvm/characters/grandle.html',
          gallery: '6',
          filter: 'ab'
        },
        {
          name: 'Shana',
          fullname: 'Shana Robinson',
          img: 'https://greyvoth.com/gvm/img/char/shana_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe General',
          style: 'Slicer',
          weapon: 'Robin',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/shana-weapon.png',
          special: 'Robe Final',
          personality: 'Confident',
          actionshot: 'Slash Redux',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Shana-full.png',
			bio: 'https://greyvoth.com/gvm/characters/shana.html',
          gallery: '7',
          filter: 'ab'
        },
//        {
//          name: 'Robe',
//          fullname: 'Robe Knight',
//          img: 'https://greyvoth.com/gvm/img/char/robe_knight_gvm_char.png',
//          house: 'Robe',
//          cityname: 'Abya Yala, Jupiter',
//          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
//          job: 'Robe Swordsman',
//          style: 'Slicer',
//          weapon: 'Dual Swords',
//          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
//          special: 'Last Fury',
//          personality: 'Confident',
//          actionshot: 'Robe Decider',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Robe-Knight-Full.png',
//          gallery: '6',
//          filter: 'ab'
//        },
//		{
//          name: 'Franker',
//          fullname: 'Franker Moon',
//          img: 'https://greyvoth.com/gvm/img/char/franker_gvm_char.png',
//          house: 'Goth',
//          cityname: 'Vortex, Gradiis',
//          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
//          job: 'Swift Gutter',
//          style: 'Sword Breaker',
//          weapon: 'Long Ax',
//          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
//          special: 'Thrice Cut',
//          personality: 'Motivated',
//          actionshot: 'Ax Fury',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Franker-Full.png',
//          gallery: '665',
//          filter: 'grad'
//        },
        {
          name: 'Christopher',
          fullname: 'Christopher',
          img: 'https://greyvoth.com/gvm/img/char/chris_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Boulevard Fighter',
          style: 'Brawler',
          weapon: 'Gloves',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/christopher-weapon.png',
          special: 'Dream Punch',
          personality: 'Quiet',
          actionshot: 'Brute Force',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
			bio: 'https://greyvoth.com/gvm/characters/chris.html',
          gallery: '8',
          filter: 'u'
        },
        {
          name: 'Seth',
          fullname: 'Seth Gate',
          img: 'https://greyvoth.com/gvm/img/char/seth_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Olan Soldier',
          style: 'Chopper',
          weapon: 'Ax',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/seth-weapon.png',
          special: 'Crossover',
          personality: 'Proud',
          actionshot: 'Cross Ax Olan',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '9',
          filter: 'u'
        },
        {
          name: 'Flow',
          fullname: 'Flow Macabre',
          img: 'https://greyvoth.com/gvm/img/char/flow_gvm_char.png',
          house: 'Dark',
          cityname: 'Ottom, Guiresphere',
          city: 'https://greyvoth.com/gvm/assets/ottom-GVM.png',
          job: 'Dark General',
          style: 'Slayer',
          weapon: 'Knives',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/flow-weapon.png',
          special: 'Lights Out',
          personality: 'Focused',
          actionshot: 'Flower\'s Thorns',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Flower-full.png',
			bio: 'https://greyvoth.com/gvm/characters/flow.html',
          gallery: '10',
          filter: 'ottom'
        },
        {
          name: 'Ripper',
          fullname: 'Kendo the Ripper',
          img: 'https://greyvoth.com/gvm/img/char/ripper_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Prisoner',
          style: 'Mace Demon',
          weapon: 'Ball and Chains',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/kendo-weapon.png',
          special: 'Choker',
          personality: 'Erradic',
          actionshot: 'Kendo\’s Chains',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '11',
          filter: 'u'
        },
        {
          name: 'Delila',
          fullname: 'Delila Gida',
          img: 'https://greyvoth.com/gvm/img/char/delila_gvm_char.png',
          house: 'None',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'Rebel Leader',
          style: 'Big Sword',
          weapon: 'Heartless',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/Delila-full.png',
          special: 'Beguile',
          personality: 'Indifferent',
          actionshot: 'Rebel\'s Blade',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Delila-full.png',
          gallery: '12',
          filter: 'lords'
        },
        {
          name: 'Pond',
          fullname: 'Pond',
          img: 'https://greyvoth.com/gvm/img/char/pond_gvm_char.png',
          house: 'Hanor',
          cityname: 'Hanor, Heaven\'s Edge',
          city: 'https://greyvoth.com/gvm/assets/hanor-GVM.png',
          job: 'The Young God',
          style: 'God Kicks',
          weapon: 'First Arrow',
          weaponshot: '',
          special: 'Halo Breach',
          personality: 'Cheerful',
          actionshot: 'Soul End',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Pond-full.png',
          gallery: '13',
          filter: 'hanor'
        },		   
//		{
//          name: 'Macabre Soldier',
//          fullname: 'Macabre Soldier',
//          img: 'https://greyvoth.com/gvm/img/char/mac_knight_gvm_char.png',
//          house: 'Dark',
//          cityname: 'Ottom, Guiresphere',
//          city: 'https://greyvoth.com/gvm/assets/ottom-GVM.png',
//          job: 'Gunner',
//          style: 'Gunner Swordsmen',
//          weapon: 'Dual Swords',
//          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/chalstolce-weapon.png',
//          special: 'Dark Punishment',
//          personality: 'Nervous',
//          actionshot: 'Gun Slice',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Mac_Knight_full.png',
//          gallery: '111',
//          filter: 'ottom'
//        },
//        {
//          name: 'Volcanis',
//          fullname: 'Volcanis',
//          img: 'https://greyvoth.com/gvm/img/char/volcanis_gvm_char.png',
//          house: 'Hanor',
//          cityname: 'Hanor, Heaven\'s Edge',
//          city: 'https://greyvoth.com/gvm/assets/hanor-GVM.png',
//          job: 'The Old God',
//          style: 'God Palm',
//          weapon: 'Flame Edge',
//          weaponshot: '',
//          special: 'God Strike',
//          personality: 'Manipulative',
//          actionshot: 'Heart of Flames',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Volcanis-full.png',
//          gallery: '14',
//          filter: 'hanor'
//        },
//        {
//          name: 'Mouse',
//          fullname: 'Ichabod Zanzbo',
//          img: 'https://greyvoth.com/gvm/img/char/mouse_gvm_char.png',
//          house: 'Weber',
//          cityname: 'Lore, Lords',
//          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
//          job: 'Olan Soldier',
//          style: 'Long Bo',
//          weapon: 'Bo',
//          weaponshot: '',
//          special: 'Striker Shot',
//          personality: 'Eager',
//          actionshot: 'Sonic Strike',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Mouse-Full.png',
//          gallery: '151',
//          filter: 'lords'
//        },	
//        {
//          name: 'Lit',
//          fullname: 'Lit Knight',
//          img: 'https://greyvoth.com/gvm/img/char/lit_gvm_char.png',
//          house: 'Weber',
//          cityname: 'Lore, Lords',
//          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
//          job: 'Sword Mage',
//          style: 'Magic Sword',
//          weapon: 'Sword & Dagger',
//          weaponshot: '',
//          special: '100 Slashes',
//          personality: 'Playful',
//          actionshot: 'Perfect Pose',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Lit-full.png',
//          gallery: '200',
//          filter: 'lords'
//        },	
//		{
//          name: 'Wolf Soldier',
//          fullname: 'Lunar Solider',
//          img: 'https://greyvoth.com/gvm/img/char/wolf_knight_gvm_char.png',
//          house: 'Wolf',
//          cityname: 'Lune, Kreis',
//          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
//          job: 'Werewolf',
//          style: 'Hard Claws',
//          weapon: 'Claw Hook',
//          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/lem-weapon.png',
//          special: 'Chronos Punch',
//          personality: 'Angry',
//          actionshot: 'Were Dive',
//          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Lunar-full.png',
//          gallery: '3',
//          filter: 'kreis sold'
//        },
        {
          name: 'Ignis',
          fullname: 'Ignis Weber',
          img: 'https://greyvoth.com/gvm/img/char/ignis_gvm_char.png',
          house: 'Weber',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'The Weber Prince',
          style: 'Devil Fists',
          weapon: 'Hand of Hell',
          weaponshot: '',
          special: 'Morne',
          personality: 'Calculating',
          actionshot: 'Demonic Punch',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '155',
          filter: 'lords'
        },   
        {
          name: 'Taur',
          fullname: 'Taur Weber',
          img: 'https://greyvoth.com/gvm/img/char/taur_gvm_char.png',
          house: 'Weber',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'Weber Queen',
          style: 'Mag Fang',
          weapon: 'Venga',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/taur-weapon.png',
          special: 'Mag Stop',
          personality: 'Loyal',
          actionshot: 'Force',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '166',
          filter: 'lords'
        },
        {
          name: 'Sol',
          fullname: 'Sol Weber',
          img: 'https://greyvoth.com/gvm/img/char/sol_gvm_char.png',
          house: 'Weber',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'The AllKing',
          style: 'God Fists',
          weapon: 'Hand of God',
          weaponshot: '',
          special: 'Cry',
          personality: 'Stubborn',
          actionshot: 'G.O.D.',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Kendo-full.png',
          gallery: '17',
          filter: 'lords'
        },
      ],

      $scope.ofighters = [
        {
          name: 'Yosh',
          fullname: 'Yosh Baskerville',
          img: 'https://greyvoth.com/gvm/img/char/yosh_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe Knight',
          style: 'Slicer',
          weapon: 'Rhetoric',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/yosh-weapon.png',
          special: 'The Answer',
          personality: 'Cautious',
          actionshot: 'Robe Glory',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/YoshVMouse.png',
			bio: 'https://greyvoth.com/gvm/characters/yosh.html',
          gallery: '4',
          filter: 'ab'
        },
        {
          name: 'Samson',
          fullname: 'Samson',
          img: 'https://greyvoth.com/gvm/img/char/samson_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Boulevard Fighter',
          style: 'Dicer',
          weapon: 'Y-Calibre',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/samson-weapon.png',
          special: 'Y Knot',
          personality: 'Bold',
//          actionshot: 'Y Slicer',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/SamsonVVoorhies.png',
			bio: 'https://greyvoth.com/gvm/characters/samson.html',
          gallery: '5',
          filter: 'u'
        },
        {
          name: 'Grandle',
          fullname: 'Grandle Robinson',
          img: 'https://greyvoth.com/gvm/img/char/grandle_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe Prince',
          style: 'Gunner',
          weapon: '9mm Handguns',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
          special: 'Robe Ammo',
          personality: 'Cocky',
          actionshot: 'Golden Punch',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/GrandleVRobe.png',
			bio: 'https://greyvoth.com/gvm/characters/grandle.html',
          gallery: '6',
          filter: 'ab'
        },
        {
          name: 'Shana',
          fullname: 'Shana Robinson',
          img: 'https://greyvoth.com/gvm/img/char/shana_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe General',
          style: 'Slicer',
          weapon: 'Robin',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/shana-weapon.png',
          special: 'Robe Final',
          personality: 'Confident',
          actionshot: 'Slash Redux',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/VolcanisVShana.png',
			bio: 'https://greyvoth.com/gvm/characters/samson.html',
          gallery: '7',
          filter: 'ab'
        },
        {
          name: 'Robe',
          fullname: 'Robe Knight',
          img: 'https://greyvoth.com/gvm/img/char/robe_knight_gvm_char.png',
          house: 'Robe',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Robe Swordsman',
          style: 'Slicer',
          weapon: 'Dual Swords',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
          special: 'Last Fury',
          personality: 'Confident',
          actionshot: 'Robe Decider',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/GrandleVRobe.png',
          gallery: '6',
          filter: 'ab'
        },
        {
          name: 'Christopher',
          fullname: 'Christopher',
          img: 'https://greyvoth.com/gvm/img/char/chris_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Boulevard Fighter',
          style: 'Brawler',
          weapon: 'Gloves',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/christopher-weapon.png',
          special: 'Dream Punch',
          personality: 'Quiet',
//          actionshot: 'Brute Force',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/ChrisVSordin.png',
			bio: 'https://greyvoth.com/gvm/characters/chris.html',
          gallery: '8',
          filter: 'u'
        },
        {
          name: 'Seth',
          fullname: 'Seth Gate',
          img: 'https://greyvoth.com/gvm/img/char/seth_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Olan Soldier',
          style: 'Chopper',
          weapon: 'Ax',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/seth-weapon.png',
          special: 'Crossover',
          personality: 'Proud',
          actionshot: 'Cross Ax Olan',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/FrankerVSeth.png',
          gallery: '9',
          filter: 'u'
        },
        {
          name: 'Flow',
          fullname: 'Flow Macabre',
          img: 'https://greyvoth.com/gvm/img/char/flow_gvm_char.png',
          house: 'Dark',
          cityname: 'Ottom, Guiresphere',
          city: 'https://greyvoth.com/gvm/assets/ottom-GVM.png',
          job: 'Dark General',
          style: 'Slayer',
          weapon: 'Knives',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/flow-weapon.png',
          special: 'Lights Out',
          personality: 'Focused',
          actionshot: 'Flower\'s Thorns',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Macabre_KnightVFlower.png',
			bio: 'https://greyvoth.com/gvm/characters/flow.html',
          gallery: '10',
          filter: 'ottom'
        },
        {
          name: 'Ripper',
          fullname: 'Kendo the Ripper',
          img: 'https://greyvoth.com/gvm/img/char/ripper_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Prisoner',
          style: 'Mace Demon',
          weapon: 'Ball and Chains',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/kendo-weapon.png',
          special: 'Choker',
          personality: 'Erradic',
          actionshot: 'Kendo\’s Chains',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/SparrowVKendo.png',
          gallery: '11',
          filter: 'u'
        },
        {
          name: 'Delila',
          fullname: 'Delila Gida',
          img: 'https://greyvoth.com/gvm/img/char/delila_gvm_char.png',
          house: 'None',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'Rebel Leader',
          style: 'Big Sword',
          weapon: 'Heartless',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/Delila-full.png',
          special: 'Beguile',
          personality: 'Indifferent',
          actionshot: 'Rebel\'s Blade',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/PondVDelila.png',
          gallery: '12',
          filter: 'lords'
        },
        {
          name: 'Eln-Delila',
          fullname: 'Eln-Delila',
          img: 'https://greyvoth.com/gvm/img/char/eln-delila_gvm_char.png',
          house: 'None',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'Eln Soldier',
          style: 'Big Sword',
          weapon: 'Heartless',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/Eln-Delila-full.png',
          special: 'Beguile',
          personality: 'Furious',
          actionshot: 'Rebel\'s Blade',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Eln-Delila-full.png',
          gallery: '120',
          filter: 'lords'
        },
		{
          name: 'Bruno',
          fullname: 'Bruno Moon',
          img: 'https://greyvoth.com/gvm/img/char/bruno_gvm_char.png',
          house: 'Goth',
          cityname: 'Vortex, Gradiis',
          city: 'https://greyvoth.com/gvm/assets/vortex-GVM.png',
          job: 'Goth Leader',
          style: 'Earth Breaker',
          weapon: 'Demons',
//          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
          special: 'Massive',
          personality: 'Obsessed',
          actionshot: 'Evil Surge',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/QuintVBruno.png',
          gallery: '660',
          filter: 'grad'
        },
						{
          name: 'Franker',
          fullname: 'Franker Moon',
          img: 'https://greyvoth.com/gvm/img/char/franker_gvm_char.png',
          house: 'Goth',
          cityname: 'Vortex, Gradiis',
          city: 'https://greyvoth.com/gvm/assets/vortex-GVM.png',
          job: 'Swift Gutter',
          style: 'Sword Breaker',
          weapon: 'Long Ax',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
          special: 'Thrice Cut',
          personality: 'Motivated',
          actionshot: 'Ax Fury',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/FrankerVSeth.png',
          gallery: '665',
          filter: 'grad'
        },
						{
          name: 'Tyree',
          fullname: 'Tyree Toth',
          img: 'https://greyvoth.com/gvm/img/char/toth_gvm_char.png',
          house: 'Goth',
          cityname: 'Vortex, Gradiis',
          city: 'https://greyvoth.com/gvm/assets/vortex-GVM.png',
          job: 'Demon Hunter',
          style: 'Large Smash',
          weapon: 'Big Hammer',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/grandle-weapon.png',
          special: 'Masher',
          personality: 'Serious',
          actionshot: 'Super Masher',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/DemoniVToth.png',
          gallery: '664',
          filter: 'grad'
        },
        {
          name: 'Sparrow',
          fullname: 'Sparrow Wilkerson',
          img: 'https://greyvoth.com/gvm/img/char/sparrow_gvm_char.png',
          house: 'None',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'Demon Hunter',
          style: 'Brute',
          weapon: 'Holis',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/shana-weapon.png',
          special: 'Demon Rig',
          personality: 'Unmoving',
          actionshot: 'Sparrow\'s Wing',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/SparrowVKendo.png',
          gallery: '7',
          filter: 'u'
        },{
          name: 'Voorhies',
          fullname: 'Voorhies Direside',
          img: 'https://greyvoth.com/gvm/img/char/voorhies_gvm_char.png',
          house: 'Mastery',
          cityname: 'Abya Yala, Jupiter',
          city: 'https://greyvoth.com/gvm/assets/jupiter-GVM.png',
          job: 'Mastery Disciple',
          style: 'Carver',
          weapon: 'Red Sword',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/voorhies-weapon.png',
          special: 'Robe Final',
          personality: 'Sleek',
          actionshot: 'Blood Drainer',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/SamsonVVoorhies.png',
          gallery: '7',
          filter: 'ab'
        },
        {
          name: 'Pond',
          fullname: 'Pond',
          img: 'https://greyvoth.com/gvm/img/char/pond_gvm_char.png',
          house: 'Hanor',
          cityname: 'Hanor, Heaven\'s Edge',
          city: 'https://greyvoth.com/gvm/assets/hanor-GVM.png',
          job: 'The Young God',
          style: 'God Kicks',
          weapon: 'First Arrow',
          weaponshot: '',
          special: 'Halo Breach',
          personality: 'Cheerful',
          actionshot: 'Soul End',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/PondVDelila.png',
          gallery: '13',
          filter: 'hanor'
        },
		{
          name: 'Sordin',
          fullname: 'Sordin',
          img: 'https://greyvoth.com/gvm/img/char/sordin_gvm_char.png',
          house: 'Hanor',
          cityname: 'Hanor, Heaven\'s Edge',
          city: 'https://greyvoth.com/gvm/assets/hanor-GVM.png',
          job: 'The Plump Knight',
          style: 'Ham Hands',
          weapon: 'Needle Point',
          weaponshot: '',
          special: 'Hard Castle',
          personality: 'Fortified',
          actionshot: 'Bleak Reaper',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/ChrisVSordin.png',
          gallery: '13',
          filter: 'hanor'
        },
		{
          name: 'Demoni',
          fullname: 'Larnx Demoni',
          img: 'https://greyvoth.com/gvm/img/char/demoni_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'The Demon Lord',
          style: 'Claw Strikes',
          weapon: 'Giant Scythe',
          weaponshot: '',
          special: 'Dark Hallows',
          personality: 'Fevered',
          actionshot: 'Soul Null',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/DemoniVToth.png',
          gallery: '13',
          filter: 'u'
        },
		{
          name: 'Macabre Soldier',
          fullname: 'Macabre Soldier',
          img: 'https://greyvoth.com/gvm/img/char/mac_knight_gvm_char.png',
          house: 'Dark',
          cityname: 'Ottom, Guiresphere',
          city: 'https://greyvoth.com/gvm/assets/ottom-GVM.png',
          job: 'Gunner',
          style: 'Gunner Swordsmen',
          weapon: 'Dual Swords',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/chalstolce-weapon.png',
          special: 'Dark Punishment',
          personality: 'Nervous',
          actionshot: 'Gun Slice',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/Macabre_KnightVFlower.png',
          gallery: '111',
          filter: 'ottom'
        },
        {
          name: 'Volcanis',
          fullname: 'Volcanis',
          img: 'https://greyvoth.com/gvm/img/char/volcanis_gvm_char.png',
          house: 'Hanor',
          cityname: 'Hanor, Heaven\'s Edge',
          city: 'https://greyvoth.com/gvm/assets/hanor-GVM.png',
          job: 'The Old God',
          style: 'God Palm',
          weapon: 'Flame Edge',
          weaponshot: '',
          special: 'God Strike',
          personality: 'Manipulative',
          actionshot: 'Heart of Flames',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/VolcanisVShana.png',
          gallery: '14',
          filter: 'hanor'
        },
        {
          name: 'Mouse',
          fullname: 'Ichabod Zanzbo',
          img: 'https://greyvoth.com/gvm/img/char/mouse_gvm_char.png',
          house: 'Weber',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'Olan Soldier',
          style: 'Long Bo',
          weapon: 'Bo',
          weaponshot: '',
          special: 'Striker Shot',
          personality: 'Eager',
          actionshot: 'Bo Strike',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/YoshVMouse.png',
          gallery: '151',
          filter: 'lords'
        },
		{
          name: 'Stormheart',
          fullname: 'Stormheart',
          img: 'https://greyvoth.com/gvm/img/char/stormheart_gvm_char.png',
          house: 'None',
          cityname: 'Unknown',
          city: 'https://greyvoth.com/gvm/assets/unknown-GVM.png',
          job: 'The Far Killer',
          style: 'Time Sword',
          weapon: 'One Handed Saw',
          weaponshot: '',
          special: 'Tremor Slice',
          personality: 'Dedicated',
          actionshot: 'Seconds',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/IgnisVStormheart.png',
          gallery: '13',
          filter: 'u'
        },	
        {
          name: 'Lit',
          fullname: 'Lit Knight',
          img: 'https://greyvoth.com/gvm/img/char/lit_gvm_char.png',
          house: 'Weber',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'Sword Mage',
          style: 'Magic Sword',
          weapon: 'Sword & Dagger',
          weaponshot: '',
          special: '100 Slashes',
          personality: 'Playful',
          actionshot: 'Perfect Pose',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/LitVLunar.png',
          gallery: '200',
          filter: 'lords'
        },	
		{
          name: 'Wolf Soldier',
          fullname: 'Lunar Solider',
          img: 'https://greyvoth.com/gvm/img/char/wolf_knight_gvm_char.png',
          house: 'Wolf',
          cityname: 'Lune, Kreis',
          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
          job: 'Werewolf',
          style: 'Hard Claws',
          weapon: 'Claw Hook',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/lem-weapon.png',
          special: 'Chronos Punch',
          personality: 'Angry',
          actionshot: 'Were Dive',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/LitVLunar.png',
          gallery: '3',
          filter: 'kreis sold'
        },
		{
          name: 'Lars',
          fullname: 'Lars',
          img: 'https://greyvoth.com/gvm/img/char/lars_gvm_char.png',
          house: 'Wolf',
          cityname: 'Lune, Kreis',
          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
          job: 'Werewolf',
          style: 'Hard Claws',
          weapon: 'Claw Hook',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/lem-weapon.png',
          special: 'Chronos Punch',
          personality: 'Angry',
          actionshot: 'Were Dive',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/LarsVMaxither.png',
          gallery: '3',
          filter: 'kreis sold'
        },
		{
          name: 'Fara',
          fullname: 'Fara Fontaine',
          img: 'https://greyvoth.com/gvm/img/char/fara_gvm_char.png',
          house: 'Goth',
          cityname: 'Vortex, Gradiis',
          city: 'https://greyvoth.com/gvm/assets/vortex-GVM.png',
          job: 'Celebrity Fighter',
          style: 'Star Smash',
          weapon: 'Diamond Claws',
          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/fara-weapon.png',
          special: 'Mincer',
          personality: 'Glam',
          actionshot: 'Super Smasher',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/BastionVFara.png',
          gallery: '669',
          filter: 'grad'
        },
		{
          name: 'Quint',
          fullname: 'Quint',
          img: 'https://greyvoth.com/gvm/img/char/quint_gvm_char.png',
          house: 'None',
          cityname: 'Lune, Kreis',
          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
          job: 'Relaxed Fighter',
          style: 'Hard Hitting',
          weapon: 'Fists and Feet',
//          weaponshot: 'https://greyvoth.com/gvm/swordsayers/img/lem-weapon.png',
          special: 'Zu Kicks',
          personality: 'Relaxed',
          actionshot: 'Round House',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/QuintVBruno.png',
          gallery: '333',
          filter: 'kreis sold'
        },
		{
          name: 'Tesha',
          fullname: 'Quint',
          img: 'https://greyvoth.com/gvm/img/char/tesha_gvm_char.png',
          house: 'None',
          cityname: 'Lune, Kreis',
          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
          job: 'Mad Merchant',
          style: 'Items',
          weapon: 'Hammer and Feet',
          special: 'Discount',
          personality: 'Angry',
          actionshot: 'Hammer Time',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/TeshaVEln-Delila.png',
          gallery: '330',
          filter: 'kreis sold'
        },
		{
          name: 'Bastion',
          fullname: 'Bastion',
          img: 'https://greyvoth.com/gvm/img/char/bastion_gvm_char.png',
          house: 'None',
          cityname: 'Lune, Kreis',
          city: 'https://greyvoth.com/gvm/assets/lune-GVM.png',
          job: 'Lion Exile',
          style: 'Cutting',
          weapon: 'Sword and Claws',
          special: '100 Slashes',
          personality: 'Still',
          actionshot: 'Claw Strike',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/BastionVFara.png',
          gallery: '333',
          filter: 'kreis sold'
        },
        {
          name: 'Ignis',
          fullname: 'Ignis Weber',
          img: 'https://greyvoth.com/gvm/img/char/ignis_gvm_char.png',
          house: 'Weber',
          cityname: 'Lore, Lords',
          city: 'https://greyvoth.com/gvm/assets/lore-GVM.png',
          job: 'The Weber Prince',
          style: 'Devil Fists',
          weapon: 'Hand of Hell',
          weaponshot: '',
          special: 'Morne',
          personality: 'Calculating',
          actionshot: 'Demonic Punch',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/IgnisVStormheart.png',
          gallery: '155',
          filter: 'lords'
        },
		{
          name: 'Maxither',
          fullname: 'Maxither',
          img: 'https://greyvoth.com/gvm/img/char/maxither_gvm_char.png',
          house: 'Hanor',
          cityname: 'Hanor, Heaven\'s Edge',
          city: 'https://greyvoth.com/gvm/assets/hanor-GVM.png',
          job: 'The Chosen God',
          style: 'God Fury',
          weapon: 'Flame Splitter',
          weaponshot: '',
          special: 'God STagger',
          personality: 'Confidient',
          actionshot: 'Heart of Fury',
          actionshotlink: 'https://greyvoth.com/gvm/swordsayers/img/LarsVMaxither.png',
          gallery: '14',
          filter: 'hanor'
        },
      ];
  });